version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - todo_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://todo_user:todo_password@db/todo"

volumes:
  todo_data:
