version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - todo_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:admin@db/todo"

volumes:
  todo_data:
